In [1]:
import warnings
warnings.filterwarnings('ignore')
import copy
import time
import pandas as pd
import numpy as np
from urllib.request import urlopen
from datetime import datetime, timedelta
import mpl_finance
import matplotlib.ticker as ticker
import matplotlib.pyplot as plt

plt.style.use('seaborn')
plt.rcParams['font.family'] = 'NanumGothicCoding'
plt.rcParams['axes.unicode_minus'] = False

C:\Users\Administrator\anaconda3\lib\site-packages\mpl_finance.py:22: DeprecationWarning:

  =================================================================

   WARNING: `mpl_finance` is deprecated:

    Please use `mplfinance` instead (no hyphen, no underscore).

    To install: `pip install --upgrade mplfinance`

   For more information, see: https://pypi.org/project/mplfinance/

  =================================================================

  category=DeprecationWarning)

In [17]:
a =pd.read_csv('data/1.csv',engine='python')
b =pd.read_csv('data/2.csv',engine='python')
c =pd.read_csv('data/3.csv',engine='python')
d =pd.read_csv('data/4.csv',engine='python')
e =pd.read_csv('data/5.csv',engine='python')
abcde = pd.concat([a,b,c,d,e])
abcde['일강수량(mm)'] = abcde['일강수량(mm)'].fillna(0)

In [21]:
# 50년 데이터
loc = {"지역":["서울특별시","서울특별시",
             '부산광역시',
             '대구광역시','대구광역시',
             '인천광역시','인천광역시','인천광역시',
             '광주광역시', 
             '대전광역시',
             '울산광역시',
             '경기도', '경기도', '경기도', '경기도', '경기도', 
             '강원도', '강원도','강원도','강원도','강원도','강원도','강원도','강원도','강원도','강원도','강원도','강원도','강원도','강원도','강원도',
             '충청북도','충청북도','충청북도','충청북도','충청북도', 
             '충청남도','충청남도','충청남도','충청남도','충청남도','충청남도', 
             '전라북도','전라북도','전라북도','전라북도','전라북도','전라북도','전라북도','전라북도','전라북도','전라북도',
             '전라남도','전라남도','전라남도','전라남도','전라남도','전라남도','전라남도','전라남도','전라남도','전라남도','전라남도','전라남도','전라남도',
             '전라남도','전라남도','전라남도',
             '경상북도','경상북도','경상북도','경상북도','경상북도','경상북도','경상북도','경상북도','경상북도','경상북도','경상북도','경상북도','경상북도','경상북도',
             '경상남도','경상남도','경상남도','경상남도','경상남도','경상남도','경상남도','경상남도','경상남도','경상남도','경상남도','경상남도','경상남도','경상남도', 
             '제주도','제주도','제주도','제주도','제주도','제주도', 
             '세종특별자치시'],
       "지점명":['관악산' ,'서울',
            '부산',
            '대구', '대구(기)',
            '강화', '백령도', '인천',
            '광주',
            '대전',
            '울산',
            '동두천', '수원', '양평', '이천', '파주', 
            '강릉', '대관령', '동해', '북강릉', '북춘천',  '삼척', '속초', '영월', '원주', '인제', '정선군', '철원', '춘천', '태백', '홍천', 
            '보은', '제천', '청주', '추풍령', '충주',
            '금산','보령','부여','서산','천안','홍성', 
            '고창','고창군','군산','남원','부안','순창군','임실','장수','전주','정읍',
            '강진군','고흥','광양시','목포','무안','보성군','순천','여수','영광군','완도','장흥','주암','진도(첨철산)',
            '진도군','해남','흑산도',
            '경주시','구미','문경','봉화','상주','안동','영덕','영주','영천','울릉도','울진','의성','청송군','포항',
            '거제','거창','김해시','남해','밀양','북창원','산청','양산시','의령군','진주','창원','통영','함양군','합천',
            '고산','서귀포','성산','성산','성산포','제주', 
            '세종'],
       '지점':[116, 108,
             159,
             143, 176,
             201, 102, 112,
             156,
             133,
             152,
             98, 119, 202, 203, 99, 
             105, 100, 106, 104, 93, 214, 90, 121, 114, 211, 217, 95, 101, 216, 212,
             226, 221, 131, 135, 127,
             238, 235, 236, 129, 232, 177,
             172, 251, 140, 247, 243, 254, 244, 248, 146, 245,
             259, 262, 266, 165, 164, 258, 174, 168, 252, 170, 260, 256, 175, 268, 261, 169,
             283, 279, 273, 271, 137, 136, 277, 272, 281, 115, 130, 278, 276, 138,
             294, 284, 253, 295, 288, 255, 289, 257, 263, 192, 155, 162, 264, 285,
             185, 189, 187, 188, 265, 184,
             239]
      }
df = pd.DataFrame(loc)
weather_date = pd.merge(abcde, df)
weather_date.rename(columns = {"평균 현지기압(hPa)":"평균 해면기압(hPa)"}, inplace=True)

In [22]:
weather_date

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),평균 풍속(m/s),평균 이슬점온도(°C),평균 상대습도(%),평균 해면기압(hPa),합계 일사량(MJ/m2),평균 전운량(1/10),지역
0,90,속초,1970-06-22,21.7,19.3,25.4,0.0,2.8,15.4,68.5,1004.9,NaN,2.0,강원도
1,90,속초,1970-06-23,21.6,19.6,25.0,0.0,2.9,16.2,71.5,1006.6,NaN,1.8,강원도
2,90,속초,1970-06-24,23.0,20.0,25.0,0.0,3.1,16.4,66.5,1004.8,NaN,3.8,강원도
3,90,속초,1970-06-25,22.7,20.1,25.4,1.5,2.5,15.2,63.0,1001.2,NaN,5.5,강원도
4,90,속초,1970-06-26,21.9,18.4,24.4,0.0,2.5,16.8,73.8,1005.0,NaN,1.8,강원도
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1339328,283,경주시,2020-06-17,21.9,16.0,27.9,0.0,1.7,15.6,69.5,1001.7,14.21,9.6,경상북도
1339329,283,경주시,2020-06-18,18.6,17.3,21.0,11.5,1.8,17.2,91.8,999.6,4.85,10.0,경상북도
1339330,283,경주시,2020-06-19,21.4,18.1,25.8,0.0,3.0,17.4,78.9,1002.7,18.83,5.6,경상북도
1339331,283,경주시,2020-06-20,21.9,17.4,28.5,0.0,1.5,17.1,76.0,1007.1,18.09,5.0,경상북도
1339332,283,경주시,2020-06-21,20.7,15.7,27.0,0.0,1.3,16.2,77.9,1005.1,17.93,2.3,경상북도

In [23]:
a = []
# for i in range(1971,2012,10):
#     weather_date = pd.read_csv(f'../data/기상청/날씨/날씨/{i}-{i+9}날씨.csv')
#     weather_date = pd.merge(weather_date, df)
#     a.append(weather_date)

weather = weather_date
#weather = weather.drop(['합계 일사량(MJ/m2)'],axis=1)
# weather = weather.dropna(how='any')

weather['연월'] = weather['일시'].str.split('-',expand=True)[0]+'-'+weather['일시'].str.split('-',expand=True)[1]
weather['연도'] = weather['일시'].str.split('-',expand=True)[0].astype(int)
weather['월'] = weather['일시'].str.split('-',expand=True)[1]
# loc_y = []
# loc_u = []
# for i in weather['지점명'].unique():
#     loc_u.append(i)
#     loc_y.append(weather.loc[weather['지점명']==f'{i}']['연도'].iloc[0])
    
# loc_df = pd.DataFrame({'지점명':loc_u,'관측 시작 연도':loc_y})
# weather = pd.merge(weather,loc_df)
weather['일강수량(mm)'] = weather['일강수량(mm)'].dropna().astype(int)
weather['평균기온(°C)'] = weather['평균기온(°C)'].dropna().astype(int)
weather['최저기온(°C)'] = weather['최저기온(°C)'].dropna().astype(int)
weather['최고기온(°C)'] = weather['최고기온(°C)'].dropna().astype(int)
weather['평균 이슬점온도(°C)'] = weather['평균 이슬점온도(°C)'].dropna().astype(int)
weather['평균 풍속(m/s)'] = weather['평균 풍속(m/s)'].dropna().astype(int)
weather['평균 상대습도(%)'] = weather['평균 상대습도(%)'].dropna().astype(int)
weather["평균 해면기압(hPa)"] = weather["평균 해면기압(hPa)"].dropna().astype(int)
weather['평균 전운량(1/10)'] = weather['평균 전운량(1/10)'].dropna().astype(int)
# weather = weather.drop(['관측 시작 연도'], 1)

k = weather.groupby(['지역', '일시']).mean().reset_index()
k = k[['지역','일시','평균기온(°C)','최저기온(°C)','최고기온(°C)','일강수량(mm)','평균 풍속(m/s)','평균 이슬점온도(°C)','평균 상대습도(%)',"평균 해면기압(hPa)",'평균 전운량(1/10)','연도']]
k = k.dropna()
k.to_csv('data/날씨통합.csv'
              , sep=","
              , index=True)

In [4]:
import pymysql
conn = pymysql.connect(host='localhost',port=3306,user='mk_database',passwd='12345',\
                       db='weather_data',charset='utf8')
curs=conn.cursor()
for i in list(np.unique(aa['지역'])):
    sql = """
    create table weather_%s(
    지역 varchar(20),
    일시 varchar(30),
    평균기온 double,
    최저기온 double,
    최고기온 double,
    일강수량 double,
    평균풍속 double,
    평균상대습도 double,
    평균해면기압 double,
    일조시간 double,
    평균전운량 double
    ) """ % i
    curs.execute(sql)
conn.commit()
conn.close()

,지역,일시,평균기온(°C),평균 상대습도(%),최고기온(°C),최저기온(°C),평균 풍속(m/s),평균 해면기압(hPa),평균 전운량(1/10),평균 이슬점온도(°C),연도,일강수량(mm)
0,강원도,1970-06-22,21.333333,70.000000,25.333333,18.666667,2.000000,1003.333333,4.000000,15.666667,1970.0,0
1,강원도,1970-06-23,22.000000,70.333333,26.666667,18.000000,1.666667,1004.666667,2.333333,16.333333,1970.0,0
2,강원도,1970-06-24,23.333333,66.000000,27.666667,19.666667,2.666667,1003.000000,3.333333,16.333333,1970.0,0
3,강원도,1970-06-25,21.666667,71.666667,25.666667,19.333333,2.000000,1000.000000,7.000000,16.333333,1970.0,1
4,강원도,1970-06-26,21.666667,74.333333,26.000000,18.000000,1.666667,1003.333333,3.666667,17.000000,1970.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
289512,충청북도,2020-06-17,22.200000,66.400000,27.600000,16.600000,0.800000,985.600000,8.200000,15.200000,2020.0,0
289513,충청북도,2020-06-18,19.600000,76.400000,22.400000,17.200000,0.600000,983.400000,9.000000,15.000000,2020.0,1
289514,충청북도,2020-06-19,21.800000,70.000000,27.800000,16.600000,0.800000,986.200000,5.000000,15.400000,2020.0,1
289515,충청북도,2020-06-20,23.000000,71.400000,28.800000,17.600000,0.800000,990.200000,4.000000,17.000000,2020.0,1
289516,충청북도,2020-06-21,24.000000,69.600000,30.800000,19.200000,0.800000,988.000000,3.200000,17.800000,2020.0,1

In [ ]:
aa= pd.read_csv('ex/날씨통합.csv')
aa = aa.iloc[:,1:]
aa = aa.dropna()
aa = aa.iloc[:,:-3]
import pymysql
conn = pymysql.connect(host='localhost',port=3306,user='mk_database',passwd='12345',\
                       db='weather_data',charset='utf8')
curs=conn.cursor()
for k in list(np.unique(aa['지역'])):
    aa1 = aa[aa['지역']=='%s' %k]
    for i in range(aa1.shape[0]):    
        sql = 'insert into weather_%s ' % k \
        +'(지역,일시,평균기온,최저기온,최고기온,일강수량,평균풍속,평균상대습도,평균해면기압,일조시간,평균전운량) values \
        ("%s","%s",%f,%f,%f,%f,%f,%f,%f,%f,%f)' %(aa1.iloc[i,0],aa1.iloc[i,1],aa1.iloc[i,2],aa1.iloc[i,3],aa1.iloc[i,4],aa1.iloc[i,5],aa1.iloc[i,6],aa1.iloc[i,7],aa1.iloc[i,8],aa1.iloc[i,9],aa1.iloc[i,10])
        curs.execute(sql)
conn.commit()
conn.close()